spring:
#  security:
#    user:
#      name: user
#      password: 1234
  #  config:
#    # .env 파일 읽어오기 관련
#    import: optional:file:.env[.properties]
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/jbc
    username: jbc
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  output:
    ansi:
      enabled: always
logging:
  level:
#    root: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
jwt:
  expiration : 86400000
  secret_key: FRbnf/Ckqv/1O8ymxg7inW4PQhIxP7xWKme9dAq426Q=
